name: Build NetHunter Kernel OnePlus 6

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        # ccache ကိုပါ အလိုအလျောက် သွင်းပေးမည့်စာကြောင်း
        sudo apt-get install -y git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-arm64 zip unzip ccache

    - name: Build the Kernel
      run: |
        export TERM=xterm
        ROOT_DIR=$(pwd)
        
        BUILD_SCRIPT=$(find . -name "build.sh" | head -n 1)
        CONFIG_FILE=$(find . -name "local.config" | head -n 1)
        BUILD_DIR=$(dirname "$BUILD_SCRIPT")
        
        if [ -n "$CONFIG_FILE" ]; then
          cp "$CONFIG_FILE" "$BUILD_DIR/"
        fi
        
        cd "$BUILD_DIR"
        chmod +x build.sh
        
        printf "T\nn\n" | ./build.sh

    - name: Upload Kernel Zip
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-OP6-Build
        path: "**/*.zip" 
        
